server:
  port: 8021
spring:
  application:
    name: oj-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ojDb?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: 'default'
        paths-to-match: '/**'
        #生成文档所需的扫包路径，一般为启动类目录
        packages-to-scan: com.ojBacked.controller
  #knife4j配置
  knife4j:
    #是否启用增强设置
    enable: true
    #开启生产环境屏蔽
    production: false
    #是否启用登录认证
    basic:
      enable: true
      username: admin
      password: 123456
    setting:
      language: zh_cn
      enable-version: true
      enable-swagger-models: true
      swagger-model-name: 用户模块

codesandbox:
  type: example
